CREATE TABLE [centralconnection] ( [CentralConnectionNum] bigint NOT NULL IDENTITY(1,1),
[ServerName] varchar(255) NOT NULL,
[DatabaseName] varchar(255) NOT NULL,
[MySqlUser] varchar(255) NOT NULL,
[MySqlPassword] varchar(255) NOT NULL,
[ServiceURI] varchar(255) NOT NULL,
[OdUser] varchar(255) NOT NULL,
[OdPassword] varchar(255) NOT NULL,
[Note] text NOT NULL,
[ItemOrder] int NOT NULL,
[WebServiceIsEcw] tinyint NOT NULL,
[ConnectionStatus] varchar(255) NOT NULL,
[HasClinicBreakdownReports] tinyint NOT NULL,
CONSTRAINT PK_CentralConnectionNum PRIMARY KEY ([CentralConnectionNum]) );