CREATE TABLE [claimcondcodelog] ( [ClaimCondCodeLogNum] bigint NOT NULL IDENTITY(1,1),
[ClaimNum] bigint NOT NULL,
[Code0] varchar(2) DEFAULT NULL,
[Code1] varchar(2) DEFAULT NULL,
[Code2] varchar(2) DEFAULT NULL,
[Code3] varchar(2) DEFAULT NULL,
[Code4] varchar(2) DEFAULT NULL,
[Code5] varchar(2) DEFAULT NULL,
[Code6] varchar(2) DEFAULT NULL,
[Code7] varchar(2) DEFAULT NULL,
[Code8] varchar(2) DEFAULT NULL,
[Code9] varchar(2) DEFAULT NULL,
[Code10] varchar(2) DEFAULT NULL,
CONSTRAINT PK_ClaimCondCodeLogNum PRIMARY KEY ([ClaimCondCodeLogNum]) );