CREATE TABLE [ehrlabresult] ( [EhrLabResultNum] bigint NOT NULL IDENTITY(1,1),
[EhrLabNum] bigint NOT NULL,
[SetIdOBX] bigint NOT NULL,
[ValueType] varchar(255) NOT NULL,
[ObservationIdentifierID] varchar(255) NOT NULL,
[ObservationIdentifierText] varchar(255) NOT NULL,
[ObservationIdentifierCodeSystemName] varchar(255) NOT NULL,
[ObservationIdentifierIDAlt] varchar(255) NOT NULL,
[ObservationIdentifierTextAlt] varchar(255) NOT NULL,
[ObservationIdentifierCodeSystemNameAlt] varchar(255) NOT NULL,
[ObservationIdentifierTextOriginal] varchar(255) NOT NULL,
[ObservationIdentifierSub] varchar(255) NOT NULL,
[ObservationValueCodedElementID] varchar(255) NOT NULL,
[ObservationValueCodedElementText] varchar(255) NOT NULL,
[ObservationValueCodedElementCodeSystemName] varchar(255) NOT NULL,
[ObservationValueCodedElementIDAlt] varchar(255) NOT NULL,
[ObservationValueCodedElementTextAlt] varchar(255) NOT NULL,
[ObservationValueCodedElementCodeSystemNameAlt] varchar(255) NOT NULL,
[ObservationValueCodedElementTextOriginal] varchar(255) NOT NULL,
[ObservationValueDateTime] varchar(255) NOT NULL,
[ObservationValueTime] time NOT NULL DEFAULT '00:00:00',
[ObservationValueComparator] varchar(255) NOT NULL,
[ObservationValueNumber1] FLOAT(53) NOT NULL,
[ObservationValueSeparatorOrSuffix] varchar(255) NOT NULL,
[ObservationValueNumber2] FLOAT(53) NOT NULL,
[ObservationValueNumeric] FLOAT(53) NOT NULL,
[ObservationValueText] varchar(255) NOT NULL,
[UnitsID] varchar(255) NOT NULL,
[UnitsText] varchar(255) NOT NULL,
[UnitsCodeSystemName] varchar(255) NOT NULL,
[UnitsIDAlt] varchar(255) NOT NULL,
[UnitsTextAlt] varchar(255) NOT NULL,
[UnitsCodeSystemNameAlt] varchar(255) NOT NULL,
[UnitsTextOriginal] varchar(255) NOT NULL,
[referenceRange] varchar(255) NOT NULL,
[AbnormalFlags] varchar(255) NOT NULL,
[ObservationResultStatus] varchar(255) NOT NULL,
[ObservationDateTime] varchar(255) NOT NULL,
[AnalysisDateTime] varchar(255) NOT NULL,
[PerformingOrganizationName] varchar(255) NOT NULL,
[PerformingOrganizationNameAssigningAuthorityNamespaceId] varchar(255) NOT NULL,
[PerformingOrganizationNameAssigningAuthorityUniversalId] varchar(255) NOT NULL,
[PerformingOrganizationNameAssigningAuthorityUniversalIdType] varchar(255) NOT NULL,
[PerformingOrganizationIdentifierTypeCode] varchar(255) NOT NULL,
[PerformingOrganizationIdentifier] varchar(255) NOT NULL,
[PerformingOrganizationAddressStreet] varchar(255) NOT NULL,
[PerformingOrganizationAddressOtherDesignation] varchar(255) NOT NULL,
[PerformingOrganizationAddressCity] varchar(255) NOT NULL,
[PerformingOrganizationAddressStateOrProvince] varchar(255) NOT NULL,
[PerformingOrganizationAddressZipOrPostalCode] varchar(255) NOT NULL,
[PerformingOrganizationAddressCountryCode] varchar(255) NOT NULL,
[PerformingOrganizationAddressAddressType] varchar(255) NOT NULL,
[PerformingOrganizationAddressCountyOrParishCode] varchar(255) NOT NULL,
[MedicalDirectorID] varchar(255) NOT NULL,
[MedicalDirectorLName] varchar(255) NOT NULL,
[MedicalDirectorFName] varchar(255) NOT NULL,
[MedicalDirectorMiddleNames] varchar(255) NOT NULL,
[MedicalDirectorSuffix] varchar(255) NOT NULL,
[MedicalDirectorPrefix] varchar(255) NOT NULL,
[MedicalDirectorAssigningAuthorityNamespaceID] varchar(255) NOT NULL,
[MedicalDirectorAssigningAuthorityUniversalID] varchar(255) NOT NULL,
[MedicalDirectorAssigningAuthorityIDType] varchar(255) NOT NULL,
[MedicalDirectorNameTypeCode] varchar(255) NOT NULL,
[MedicalDirectorIdentifierTypeCode] varchar(255) NOT NULL,
CONSTRAINT PK_EhrLabResultNum PRIMARY KEY ([EhrLabResultNum])
);

GO
CREATE NONCLUSTERED INDEX [IX_EhrLabNum] ON [ehrlabresult] ([EhrLabNum]);

GO
CREATE NONCLUSTERED INDEX [IX_SetIdOBX] ON [ehrlabresult] ([SetIdOBX]);