CREATE TABLE [ehrtrigger] ( [EhrTriggerNum] bigint NOT NULL IDENTITY(1,1),
[Description] varchar(255) NOT NULL,
[ProblemSnomedList] text NOT NULL,
[ProblemIcd9List] text NOT NULL,
[ProblemIcd10List] text NOT NULL,
[ProblemDefNumList] text NOT NULL,
[MedicationNumList] text NOT NULL,
[RxCuiList] text NOT NULL,
[CvxList] text NOT NULL,
[AllergyDefNumList] text NOT NULL,
[DemographicsList] text NOT NULL,
[LabLoincList] text NOT NULL,
[VitalLoincList] text NOT NULL,
[Instructions] text NOT NULL,
[Bibliography] text NOT NULL,
[Cardinality] tinyint NOT NULL,
CONSTRAINT PK_EhrTriggerNum PRIMARY KEY ([EhrTriggerNum]) );