CREATE TABLE [hl7def] ( [HL7DefNum] bigint NOT NULL IDENTITY(1,1),
[Description] varchar(255) NOT NULL,
[ModeTx] tinyint NOT NULL,
[IncomingFolder] varchar(255) NOT NULL,
[OutgoingFolder] varchar(255) NOT NULL,
[IncomingPort] varchar(255) NOT NULL,
[OutgoingIpPort] varchar(255) NOT NULL,
[FieldSeparator] varchar(5) NOT NULL,
[ComponentSeparator] varchar(5) NOT NULL,
[SubcomponentSeparator] varchar(5) NOT NULL,
[RepetitionSeparator] varchar(5) NOT NULL,
[EscapeCharacter] varchar(5) NOT NULL,
[IsInternal] tinyint NOT NULL,
[InternalType] varchar(255) NOT NULL,
[InternalTypeVersion] varchar(50) NOT NULL,
[IsEnabled] tinyint NOT NULL,
[Note] text NOT NULL,
[HL7Server] varchar(255) NOT NULL,
[HL7ServiceName] varchar(255) NOT NULL,
[ShowDemographics] tinyint NOT NULL,
[ShowAppts] tinyint NOT NULL,
[ShowAccount] tinyint NOT NULL,
[IsQuadAsToothNum] tinyint NOT NULL,
[LabResultImageCat] bigint NOT NULL,
[SftpUsername] varchar(255) NOT NULL,
[SftpPassword] varchar(255) NOT NULL,
[SftpInSocket] varchar(255) NOT NULL,
[HasLongDCodes] tinyint NOT NULL,
[IsProcApptEnforced] tinyint NOT NULL,
CONSTRAINT PK_HL7DefNum PRIMARY KEY ([HL7DefNum])
);

GO
CREATE NONCLUSTERED INDEX [IX_LabResultImageCat] ON [hl7def] ([LabResultImageCat]);