//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace PractxAPI.Controllers
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IPractxApiController
    {

        /// <summary>
        /// Retrieve a school class
        /// </summary>


        /// <returns>Class retrieved</returns>

        System.Threading.Tasks.Task<SchoolClass> SchoolClassesGETAsync(int id);

        /// <summary>
        /// Update a school class
        /// </summary>


        /// <returns>Class updated</returns>

        System.Threading.Tasks.Task<SchoolClass> SchoolClassesPUTAsync(int id, SchoolClassUpdate body);

        /// <summary>
        /// Remove a school class
        /// </summary>


        /// <returns>Class deleted</returns>

        System.Threading.Tasks.Task SchoolClassesDELETEAsync(int id);

        /// <summary>
        /// Retrieve a requirement
        /// </summary>


        /// <returns>Requirement retrieved</returns>

        System.Threading.Tasks.Task<Requirement> RequirementsGETAsync(int id);

        /// <summary>
        /// Update a requirement
        /// </summary>


        /// <returns>Requirement updated</returns>

        System.Threading.Tasks.Task<Requirement> RequirementsPUTAsync(int id, RequirementUpdate body);

        /// <summary>
        /// Remove a requirement
        /// </summary>


        /// <returns>Requirement deleted</returns>

        System.Threading.Tasks.Task RequirementsDELETEAsync(int id);

        /// <summary>
        /// List providers
        /// </summary>

        /// <returns>Providers listed</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Provider>> ProvidersAsync();

        /// <summary>
        /// List dispensary supplies for a provider
        /// </summary>


        /// <returns>Supplies listed</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<DispenseSupply>> DispSuppliesAsync(int provNum);

        /// <summary>
        /// List clinics
        /// </summary>

        /// <returns>Clinics listed</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Clinic>> ClinicsAsync();

        /// <summary>
        /// List web scheduling carrier rules for a clinic
        /// </summary>


        /// <returns>Rules listed</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<WebSchedCarrierRule>> WebSchedCarrierRulesAsync(int clinicNum);

        /// <summary>
        /// Copy carrier rules from one clinic to others
        /// </summary>


        /// <returns>Rules copied</returns>

        System.Threading.Tasks.Task CopyAsync(CopyCarrierRules body);

        /// <summary>
        /// List insurance blue book rules
        /// </summary>

        /// <returns>Rules listed</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<InsuranceBlueBookRule>> InsBluebookRulesAllAsync();

        /// <summary>
        /// Update an insurance blue book rule
        /// </summary>


        /// <returns>Rule updated</returns>

        System.Threading.Tasks.Task<InsuranceBlueBookRule> InsBluebookRulesAsync(int id, InsuranceBlueBookRuleUpdate body);

        /// <summary>
        /// List prescription templates
        /// </summary>

        /// <returns>Templates listed</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<PrescriptionTemplate>> RxDefsAllAsync();

        /// <summary>
        /// Create a prescription template
        /// </summary>


        /// <returns>Template created</returns>

        System.Threading.Tasks.Task<PrescriptionTemplate> RxDefsPOSTAsync(PrescriptionTemplateCreate body);

        /// <summary>
        /// Update a prescription template
        /// </summary>


        /// <returns>Template updated</returns>

        System.Threading.Tasks.Task<PrescriptionTemplate> RxDefsPUTAsync(int id, PrescriptionTemplateUpdate body);

        /// <summary>
        /// Remove a prescription template
        /// </summary>


        /// <returns>Template removed</returns>

        System.Threading.Tasks.Task RxDefsDELETEAsync(int id);

        /// <summary>
        /// Retrieve insurance benefit notes
        /// </summary>


        /// <returns>Notes retrieved</returns>

        System.Threading.Tasks.Task<InsuranceBenefitNotes> InsBenefitNotesGETAsync(int id);

        /// <summary>
        /// Update insurance benefit notes
        /// </summary>


        /// <returns>Notes updated</returns>

        System.Threading.Tasks.Task<InsuranceBenefitNotes> InsBenefitNotesPUTAsync(int id, InsuranceBenefitNotesUpdate body);

        /// <summary>
        /// Retrieve an appointment view
        /// </summary>


        /// <returns>View retrieved</returns>

        System.Threading.Tasks.Task<AppointmentView> ApptViewsGETAsync(int id);

        /// <summary>
        /// Update an appointment view
        /// </summary>


        /// <returns>View updated</returns>

        System.Threading.Tasks.Task<AppointmentView> ApptViewsPUTAsync(int id, AppointmentViewUpdate body);

        /// <summary>
        /// Remove an appointment view
        /// </summary>


        /// <returns>View deleted</returns>

        System.Threading.Tasks.Task ApptViewsDELETEAsync(int id);

        /// <summary>
        /// Retrieve a patient
        /// </summary>


        /// <returns>Patient retrieved</returns>

        System.Threading.Tasks.Task<Patient> PatientsAsync(int id);

        /// <summary>
        /// Update a patient's email
        /// </summary>


        /// <returns>Email updated</returns>

        System.Threading.Tasks.Task EmailAsync(int id, PatientEmailUpdate body);

        /// <summary>
        /// List forms for a patient
        /// </summary>


        /// <returns>Forms listed</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<PatientForm>> FormsAllAsync(int id);

        /// <summary>
        /// Add a patient form
        /// </summary>


        /// <returns>Form added</returns>

        System.Threading.Tasks.Task<PatientForm> FormsAsync(int id, PatientFormCreate body);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public partial class PractxApiController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IPractxApiController _implementation;

        public PractxApiController(IPractxApiController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// Retrieve a school class
        /// </summary>
        /// <returns>Class retrieved</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/school-classes/{id}")]
        public System.Threading.Tasks.Task<SchoolClass> SchoolClassesGET(int id)
        {

            return _implementation.SchoolClassesGETAsync(id);
        }

        /// <summary>
        /// Update a school class
        /// </summary>
        /// <returns>Class updated</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/school-classes/{id}")]
        public System.Threading.Tasks.Task<SchoolClass> SchoolClassesPUT(int id, [Microsoft.AspNetCore.Mvc.FromBody] SchoolClassUpdate body)
        {

            return _implementation.SchoolClassesPUTAsync(id, body);
        }

        /// <summary>
        /// Remove a school class
        /// </summary>
        /// <returns>Class deleted</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("api/school-classes/{id}")]
        public System.Threading.Tasks.Task SchoolClassesDELETE(int id)
        {

            return _implementation.SchoolClassesDELETEAsync(id);
        }

        /// <summary>
        /// Retrieve a requirement
        /// </summary>
        /// <returns>Requirement retrieved</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/requirements/{id}")]
        public System.Threading.Tasks.Task<Requirement> RequirementsGET(int id)
        {

            return _implementation.RequirementsGETAsync(id);
        }

        /// <summary>
        /// Update a requirement
        /// </summary>
        /// <returns>Requirement updated</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/requirements/{id}")]
        public System.Threading.Tasks.Task<Requirement> RequirementsPUT(int id, [Microsoft.AspNetCore.Mvc.FromBody] RequirementUpdate body)
        {

            return _implementation.RequirementsPUTAsync(id, body);
        }

        /// <summary>
        /// Remove a requirement
        /// </summary>
        /// <returns>Requirement deleted</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("api/requirements/{id}")]
        public System.Threading.Tasks.Task RequirementsDELETE(int id)
        {

            return _implementation.RequirementsDELETEAsync(id);
        }

        /// <summary>
        /// List providers
        /// </summary>
        /// <returns>Providers listed</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/providers")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Provider>> Providers()
        {

            return _implementation.ProvidersAsync();
        }

        /// <summary>
        /// List dispensary supplies for a provider
        /// </summary>
        /// <returns>Supplies listed</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/disp-supplies")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<DispenseSupply>> DispSupplies([Microsoft.AspNetCore.Mvc.FromQuery] int provNum)
        {

            return _implementation.DispSuppliesAsync(provNum);
        }

        /// <summary>
        /// List clinics
        /// </summary>
        /// <returns>Clinics listed</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/clinics")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Clinic>> Clinics()
        {

            return _implementation.ClinicsAsync();
        }

        /// <summary>
        /// List web scheduling carrier rules for a clinic
        /// </summary>
        /// <returns>Rules listed</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/web-sched-carrier-rules")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<WebSchedCarrierRule>> WebSchedCarrierRules([Microsoft.AspNetCore.Mvc.FromQuery] int clinicNum)
        {

            return _implementation.WebSchedCarrierRulesAsync(clinicNum);
        }

        /// <summary>
        /// Copy carrier rules from one clinic to others
        /// </summary>
        /// <returns>Rules copied</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/web-sched-carrier-rules/copy")]
        public System.Threading.Tasks.Task Copy([Microsoft.AspNetCore.Mvc.FromBody] CopyCarrierRules body)
        {

            return _implementation.CopyAsync(body);
        }

        /// <summary>
        /// List insurance blue book rules
        /// </summary>
        /// <returns>Rules listed</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/ins-bluebook-rules")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<InsuranceBlueBookRule>> InsBluebookRulesAll()
        {

            return _implementation.InsBluebookRulesAllAsync();
        }

        /// <summary>
        /// Update an insurance blue book rule
        /// </summary>
        /// <returns>Rule updated</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/ins-bluebook-rules/{id}")]
        public System.Threading.Tasks.Task<InsuranceBlueBookRule> InsBluebookRules(int id, [Microsoft.AspNetCore.Mvc.FromBody] InsuranceBlueBookRuleUpdate body)
        {

            return _implementation.InsBluebookRulesAsync(id, body);
        }

        /// <summary>
        /// List prescription templates
        /// </summary>
        /// <returns>Templates listed</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/rx-defs")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<PrescriptionTemplate>> RxDefsAll()
        {

            return _implementation.RxDefsAllAsync();
        }

        /// <summary>
        /// Create a prescription template
        /// </summary>
        /// <returns>Template created</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/rx-defs")]
        public System.Threading.Tasks.Task<PrescriptionTemplate> RxDefsPOST([Microsoft.AspNetCore.Mvc.FromBody] PrescriptionTemplateCreate body)
        {

            return _implementation.RxDefsPOSTAsync(body);
        }

        /// <summary>
        /// Update a prescription template
        /// </summary>
        /// <returns>Template updated</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/rx-defs/{id}")]
        public System.Threading.Tasks.Task<PrescriptionTemplate> RxDefsPUT(int id, [Microsoft.AspNetCore.Mvc.FromBody] PrescriptionTemplateUpdate body)
        {

            return _implementation.RxDefsPUTAsync(id, body);
        }

        /// <summary>
        /// Remove a prescription template
        /// </summary>
        /// <returns>Template removed</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("api/rx-defs/{id}")]
        public System.Threading.Tasks.Task RxDefsDELETE(int id)
        {

            return _implementation.RxDefsDELETEAsync(id);
        }

        /// <summary>
        /// Retrieve insurance benefit notes
        /// </summary>
        /// <returns>Notes retrieved</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/ins-benefit-notes/{id}")]
        public System.Threading.Tasks.Task<InsuranceBenefitNotes> InsBenefitNotesGET(int id)
        {

            return _implementation.InsBenefitNotesGETAsync(id);
        }

        /// <summary>
        /// Update insurance benefit notes
        /// </summary>
        /// <returns>Notes updated</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/ins-benefit-notes/{id}")]
        public System.Threading.Tasks.Task<InsuranceBenefitNotes> InsBenefitNotesPUT(int id, [Microsoft.AspNetCore.Mvc.FromBody] InsuranceBenefitNotesUpdate body)
        {

            return _implementation.InsBenefitNotesPUTAsync(id, body);
        }

        /// <summary>
        /// Retrieve an appointment view
        /// </summary>
        /// <returns>View retrieved</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/appt-views/{id}")]
        public System.Threading.Tasks.Task<AppointmentView> ApptViewsGET(int id)
        {

            return _implementation.ApptViewsGETAsync(id);
        }

        /// <summary>
        /// Update an appointment view
        /// </summary>
        /// <returns>View updated</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/appt-views/{id}")]
        public System.Threading.Tasks.Task<AppointmentView> ApptViewsPUT(int id, [Microsoft.AspNetCore.Mvc.FromBody] AppointmentViewUpdate body)
        {

            return _implementation.ApptViewsPUTAsync(id, body);
        }

        /// <summary>
        /// Remove an appointment view
        /// </summary>
        /// <returns>View deleted</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("api/appt-views/{id}")]
        public System.Threading.Tasks.Task ApptViewsDELETE(int id)
        {

            return _implementation.ApptViewsDELETEAsync(id);
        }

        /// <summary>
        /// Retrieve a patient
        /// </summary>
        /// <returns>Patient retrieved</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/patients/{id}")]
        public System.Threading.Tasks.Task<Patient> Patients(int id)
        {

            return _implementation.PatientsAsync(id);
        }

        /// <summary>
        /// Update a patient's email
        /// </summary>
        /// <returns>Email updated</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/patients/{id}/email")]
        public System.Threading.Tasks.Task Email(int id, [Microsoft.AspNetCore.Mvc.FromBody] PatientEmailUpdate body)
        {

            return _implementation.EmailAsync(id, body);
        }

        /// <summary>
        /// List forms for a patient
        /// </summary>
        /// <returns>Forms listed</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/patients/{id}/forms")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<PatientForm>> FormsAll(int id)
        {

            return _implementation.FormsAllAsync(id);
        }

        /// <summary>
        /// Add a patient form
        /// </summary>
        /// <returns>Form added</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/patients/{id}/forms")]
        public System.Threading.Tasks.Task<PatientForm> Forms(int id, [Microsoft.AspNetCore.Mvc.FromBody] PatientFormCreate body)
        {

            return _implementation.FormsAsync(id, body);
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SchoolClass
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("graduationYear")]
        public int GraduationYear { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SchoolClassUpdate
    {

        [System.Text.Json.Serialization.JsonPropertyName("graduationYear")]
        public int GraduationYear { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Requirement
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RequirementUpdate
    {

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Provider
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lastName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string LastName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("firstName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string FirstName { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DispenseSupply
    {

        [System.Text.Json.Serialization.JsonPropertyName("dateDispensed")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset DateDispensed { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("quantity")]
        public int Quantity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("note")]
        public string Note { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Clinic
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("abbreviation")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Abbreviation { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class WebSchedCarrierRule
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("carrierName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CarrierName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DisplayName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rule")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Rule { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        public string Message { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CopyCarrierRules
    {

        [System.Text.Json.Serialization.JsonPropertyName("fromClinicId")]
        public int FromClinicId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("toClinicIds")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.List<int> ToClinicIds { get; set; } = new System.Collections.Generic.List<int>();

        [System.Text.Json.Serialization.JsonPropertyName("overrideExisting")]
        public bool OverrideExisting { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InsuranceBlueBookRule
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ruleType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RuleType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("matching")]
        public string Matching { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("limitType")]
        public string LimitType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("limitValue")]
        public string LimitValue { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InsuranceBlueBookRuleUpdate
    {

        [System.Text.Json.Serialization.JsonPropertyName("ruleType")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RuleType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("matching")]
        public string Matching { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("limitType")]
        public string LimitType { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("limitValue")]
        public string LimitValue { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PrescriptionTemplate
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("drug")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Drug { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isControlled")]
        public bool IsControlled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("directions")]
        public string Directions { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dispenseAmount")]
        public string DispenseAmount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("refills")]
        public string Refills { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("notes")]
        public string Notes { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PrescriptionTemplateCreate
    {

        [System.Text.Json.Serialization.JsonPropertyName("drug")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Drug { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isControlled")]
        public bool IsControlled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("directions")]
        public string Directions { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dispenseAmount")]
        public string DispenseAmount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("refills")]
        public string Refills { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("notes")]
        public string Notes { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PrescriptionTemplateUpdate
    {

        [System.Text.Json.Serialization.JsonPropertyName("drug")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Drug { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isControlled")]
        public bool IsControlled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("directions")]
        public string Directions { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dispenseAmount")]
        public string DispenseAmount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("refills")]
        public string Refills { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("notes")]
        public string Notes { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InsuranceBenefitNotes
    {

        [System.Text.Json.Serialization.JsonPropertyName("benefitNotes")]
        public string BenefitNotes { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InsuranceBenefitNotesUpdate
    {

        [System.Text.Json.Serialization.JsonPropertyName("benefitNotes")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BenefitNotes { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppointmentView
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rowsPerIncrement")]
        public int RowsPerIncrement { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("minOperatoryWidth")]
        public int MinOperatoryWidth { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("scrollStartTime")]
        public string ScrollStartTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dynamicScroll")]
        public bool DynamicScroll { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("disableAppointmentBubbles")]
        public bool DisableAppointmentBubbles { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onlyScheduledProviders")]
        public bool OnlyScheduledProviders { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onlyScheduledProviderDays")]
        public bool OnlyScheduledProviderDays { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onlyScheduleBeforeTime")]
        public string OnlyScheduleBeforeTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onlyScheduleAfterTime")]
        public string OnlyScheduleAfterTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("clinicId")]
        public int ClinicId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("waitingRoomName")]
        public string WaitingRoomName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("stackBehaviorUpperRight")]
        public string StackBehaviorUpperRight { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("stackBehaviorLowerRight")]
        public string StackBehaviorLowerRight { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppointmentViewUpdate
    {

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rowsPerIncrement")]
        public int RowsPerIncrement { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("minOperatoryWidth")]
        public int MinOperatoryWidth { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("scrollStartTime")]
        public string ScrollStartTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dynamicScroll")]
        public bool DynamicScroll { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("disableAppointmentBubbles")]
        public bool DisableAppointmentBubbles { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onlyScheduledProviders")]
        public bool OnlyScheduledProviders { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onlyScheduledProviderDays")]
        public bool OnlyScheduledProviderDays { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onlyScheduleBeforeTime")]
        public string OnlyScheduleBeforeTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onlyScheduleAfterTime")]
        public string OnlyScheduleAfterTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("clinicId")]
        public int ClinicId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("waitingRoomName")]
        public string WaitingRoomName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("stackBehaviorUpperRight")]
        public string StackBehaviorUpperRight { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("stackBehaviorLowerRight")]
        public string StackBehaviorLowerRight { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Patient
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Email { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PatientEmailUpdate
    {

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Email { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PatientForm
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dateTime")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DateTime { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PatientFormCreate
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTimeOffset>
    {
        public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var dateTime = reader.GetString();
            if (dateTime == null)
            {
                throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
            }

            return System.DateTimeOffset.Parse(dateTime);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
        }
    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765