CREATE TABLE [employee] ( [EmployeeNum] bigint NOT NULL IDENTITY(1,1),
[LName] varchar(255) DEFAULT '',
[FName] varchar(255) DEFAULT '',
[MiddleI] varchar(255) DEFAULT '',
[IsHidden] tinyint NOT NULL DEFAULT 0,
[ClockStatus] varchar(255) DEFAULT '',
[PhoneExt] int NOT NULL,
[PayrollID] varchar(255) NOT NULL,
[WirelessPhone] varchar(255) NOT NULL,
[EmailWork] varchar(255) NOT NULL,
[EmailPersonal] varchar(255) NOT NULL,
[IsFurloughed] tinyint NOT NULL,
[IsWorkingHome] tinyint NOT NULL,
[ReportsTo] bigint NOT NULL,
CONSTRAINT PK_EmployeeNum PRIMARY KEY ([EmployeeNum]) );