CREATE TABLE [pharmacy] ( [PharmacyNum] bigint NOT NULL IDENTITY(1,1),
[PharmID] varchar(255) DEFAULT NULL,
[StoreName] varchar(255) DEFAULT NULL,
[Phone] varchar(255) DEFAULT NULL,
[Fax] varchar(255) DEFAULT NULL,
[Address] varchar(255) DEFAULT NULL,
[Address2] varchar(255) DEFAULT NULL,
[City] varchar(255) DEFAULT NULL,
[State] varchar(255) DEFAULT NULL,
[Zip] varchar(255) DEFAULT NULL,
[Note] text DEFAULT NULL,
[DateTStamp] timestamp NOT NULL DEFAULT GETDATE(),-- ON UPDATE GETDATE(),
CONSTRAINT PK_PharmacyNum PRIMARY KEY ([PharmacyNum]) );