CREATE TABLE `appointment` (
  `AptNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `AptStatus` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `Pattern` varchar(255) DEFAULT '',
  `Confirmed` bigint(20) NOT NULL,
  `TimeLocked` tinyint(1) NOT NULL,
  `Op` bigint(20) NOT NULL,
  `Note` text DEFAULT NULL,
  `ProvNum` bigint(20) NOT NULL,
  `ProvHyg` bigint(20) NOT NULL,
  `AptDateTime` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `NextAptNum` bigint(20) NOT NULL,
  `UnschedStatus` bigint(20) NOT NULL,
  `IsNewPatient` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `ProcDescript` varchar(255) DEFAULT '',
  `Assistant` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `IsHygiene` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `DateTStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `DateTimeArrived` datetime NOT NULL,
  `DateTimeSeated` datetime NOT NULL,
  `DateTimeDismissed` datetime NOT NULL,
  `InsPlan1` bigint(20) NOT NULL,
  `InsPlan2` bigint(20) NOT NULL,
  `DateTimeAskedToArrive` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ProcsColored` text NOT NULL,
  `ColorOverride` int(11) NOT NULL,
  `AppointmentTypeNum` bigint(20) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateTEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `Priority` tinyint(4) NOT NULL,
  `ProvBarText` varchar(60) NOT NULL,
  `PatternSecondary` varchar(255) NOT NULL,
  `SecurityHash` varchar(255) NOT NULL,
  PRIMARY KEY (`AptNum`),
  KEY `indexPatNum` (`PatNum`),
  KEY `indexNextAptNum` (`NextAptNum`),
  KEY `indexProvNum` (`ProvNum`),
  KEY `indexProvHyg` (`ProvHyg`),
  KEY `indexAptDateTime` (`AptDateTime`),
  KEY `InsPlan1` (`InsPlan1`),
  KEY `InsPlan2` (`InsPlan2`),
  KEY `DateTimeArrived` (`DateTimeArrived`),
  KEY `AppointmentTypeNum` (`AppointmentTypeNum`),
  KEY `Op` (`Op`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`),
  KEY `StatusDate` (`AptStatus`,`AptDateTime`,`ClinicNum`),
  KEY `Priority` (`Priority`),
  KEY `UnschedStatus` (`UnschedStatus`),
  KEY `ClinicNum` (`ClinicNum`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;