CREATE TABLE `apptreminderrule` (
  `ApptReminderRuleNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `TypeCur` tinyint(4) NOT NULL,
  `TSPrior` bigint(20) NOT NULL,
  `SendOrder` varchar(255) NOT NULL,
  `IsSendAll` tinyint(4) NOT NULL,
  `TemplateSMS` text NOT NULL,
  `TemplateEmailSubject` text NOT NULL,
  `TemplateEmail` text NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `TemplateSMSAggShared` text NOT NULL,
  `TemplateSMSAggPerAppt` text NOT NULL,
  `TemplateEmailSubjAggShared` text NOT NULL,
  `TemplateEmailAggShared` text NOT NULL,
  `TemplateEmailAggPerAppt` text NOT NULL,
  `DoNotSendWithin` bigint(20) NOT NULL,
  `IsEnabled` tinyint(4) NOT NULL,
  `TemplateAutoReply` text NOT NULL,
  `TemplateAutoReplyAgg` text NOT NULL,
  `IsAutoReplyEnabled` tinyint(4) NOT NULL,
  `Language` varchar(255) NOT NULL,
  `TemplateComeInMessage` text NOT NULL,
  `EmailTemplateType` varchar(255) NOT NULL,
  `AggEmailTemplateType` varchar(255) NOT NULL,
  `IsSendForMinorsBirthday` tinyint(4) NOT NULL,
  `EmailHostingTemplateNum` bigint(20) NOT NULL,
  `MinorAge` int(11) NOT NULL,
  `TemplateFailureAutoReply` text NOT NULL,
  `SendMultipleInvites` tinyint(4) NOT NULL,
  `TimeSpanMultipleInvites` bigint(20) NOT NULL,
  PRIMARY KEY (`ApptReminderRuleNum`),
  KEY `TSPrior` (`TSPrior`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `EmailHostingTemplateNum` (`EmailHostingTemplateNum`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;