CREATE TABLE `apptthankyousent` (
  `ApptThankYouSentNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `ApptNum` bigint(20) NOT NULL,
  `ApptDateTime` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ApptSecDateTEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TSPrior` bigint(20) NOT NULL,
  `ApptReminderRuleNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `ResponseDescript` text NOT NULL,
  `DateTimeThankYouTransmit` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ShortGUID` varchar(255) NOT NULL,
  `SendStatus` tinyint(4) NOT NULL,
  `DoNotResend` tinyint(4) NOT NULL,
  `MessageType` tinyint(4) NOT NULL,
  `MessageFk` bigint(20) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeSent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  PRIMARY KEY (`ApptThankYouSentNum`),
  KEY `ApptNum` (`ApptNum`),
  KEY `TSPrior` (`TSPrior`),
  KEY `ApptReminderRuleNum` (`ApptReminderRuleNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `PatNum` (`PatNum`),
  KEY `ApptDateTime` (`ApptDateTime`),
  KEY `MessageFk` (`MessageFk`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;