CREATE TABLE `asapcomm` (
  `AsapCommNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `FKey` bigint(20) NOT NULL,
  `FKeyType` tinyint(4) NOT NULL,
  `ScheduleNum` bigint(20) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `ShortGUID` varchar(255) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeExpire` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeSmsScheduled` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SmsSendStatus` tinyint(4) NOT NULL,
  `EmailSendStatus` tinyint(4) NOT NULL,
  `DateTimeSmsSent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeEmailSent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `EmailMessageNum` bigint(20) NOT NULL,
  `ResponseStatus` tinyint(4) NOT NULL,
  `DateTimeOrig` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TemplateText` text NOT NULL,
  `TemplateEmail` text NOT NULL,
  `TemplateEmailSubj` varchar(100) NOT NULL,
  `Note` text NOT NULL,
  `GuidMessageToMobile` text NOT NULL,
  `EmailTemplateType` varchar(255) NOT NULL,
  PRIMARY KEY (`AsapCommNum`),
  KEY `FKey` (`FKey`),
  KEY `ScheduleNum` (`ScheduleNum`),
  KEY `PatNum` (`PatNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `EmailMessageNum` (`EmailMessageNum`),
  KEY `SmsSendStatus` (`SmsSendStatus`),
  KEY `EmailSendStatus` (`EmailSendStatus`),
  KEY `ShortGUID` (`ShortGUID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;