CREATE TABLE `benefit` (
  `BenefitNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PlanNum` bigint(20) NOT NULL,
  `PatPlanNum` bigint(20) NOT NULL,
  `CovCatNum` bigint(20) NOT NULL,
  `BenefitType` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `Percent` tinyint(4) NOT NULL,
  `MonetaryAmt` double NOT NULL DEFAULT 0,
  `TimePeriod` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `QuantityQualifier` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `Quantity` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `CodeNum` bigint(20) NOT NULL,
  `CoverageLevel` int(11) NOT NULL,
  `SecDateTEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `CodeGroupNum` bigint(20) NOT NULL,
  `TreatArea` tinyint(4) NOT NULL,
  PRIMARY KEY (`BenefitNum`),
  KEY `indexPlanNum` (`PlanNum`),
  KEY `indexPatPlanNum` (`PatPlanNum`),
  KEY `CovCatNum` (`CovCatNum`),
  KEY `BenefitType` (`BenefitType`),
  KEY `Percent` (`Percent`),
  KEY `MonetaryAmt` (`MonetaryAmt`),
  KEY `TimePeriod` (`TimePeriod`),
  KEY `QuantityQualifier` (`QuantityQualifier`),
  KEY `Quantity` (`Quantity`),
  KEY `CodeNum` (`CodeNum`),
  KEY `CoverageLevel` (`CoverageLevel`),
  KEY `SecDateTEntry` (`SecDateTEntry`),
  KEY `SecDateTEdit` (`SecDateTEdit`),
  KEY `CodeGroupNum` (`CodeGroupNum`)
) ENGINE=MyISAM AUTO_INCREMENT=33 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;