CREATE TABLE `carecreditwebresponse` (
  `CareCreditWebResponseNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `PayNum` bigint(20) NOT NULL,
  `RefNumber` varchar(255) NOT NULL,
  `Amount` double NOT NULL,
  `WebToken` varchar(255) NOT NULL,
  `ProcessingStatus` varchar(255) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimePending` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeCompleted` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeExpired` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeLastError` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `LastResponseStr` text NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `ServiceType` varchar(255) NOT NULL,
  `TransType` varchar(255) NOT NULL,
  `MerchantNumber` varchar(20) NOT NULL,
  `HasLogged` tinyint(4) NOT NULL,
  PRIMARY KEY (`CareCreditWebResponseNum`),
  KEY `PatNum` (`PatNum`),
  KEY `PayNum` (`PayNum`),
  KEY `ClinicNum` (`ClinicNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;