CREATE TABLE `carrier` (
  `CarrierNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `CarrierName` varchar(255) DEFAULT '',
  `Address` varchar(255) DEFAULT '',
  `Address2` varchar(255) DEFAULT '',
  `City` varchar(255) DEFAULT '',
  `State` varchar(255) DEFAULT '',
  `Zip` varchar(255) DEFAULT '',
  `Phone` varchar(255) DEFAULT '',
  `ElectID` varchar(255) DEFAULT '',
  `NoSendElect` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `IsCDA` tinyint(3) unsigned NOT NULL,
  `CDAnetVersion` varchar(100) DEFAULT '',
  `CanadianNetworkNum` bigint(20) NOT NULL,
  `IsHidden` tinyint(4) NOT NULL,
  `CanadianEncryptionMethod` tinyint(4) NOT NULL,
  `CanadianSupportedTypes` int(11) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateEntry` date NOT NULL DEFAULT '0001-01-01',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `TIN` varchar(255) NOT NULL,
  `CarrierGroupName` bigint(20) NOT NULL,
  `ApptTextBackColor` int(11) NOT NULL,
  `IsCoinsuranceInverted` tinyint(4) NOT NULL,
  `TrustedEtransFlags` tinyint(4) NOT NULL,
  `CobInsPaidBehaviorOverride` tinyint(4) NOT NULL,
  `EraAutomationOverride` tinyint(4) NOT NULL,
  `OrthoInsPayConsolidate` tinyint(4) NOT NULL,
  PRIMARY KEY (`CarrierNum`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`),
  KEY `CarrierNumName` (`CarrierNum`,`CarrierName`),
  KEY `CanadianNetworkNum` (`CanadianNetworkNum`),
  KEY `CarrierGroupName` (`CarrierGroupName`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;