CREATE TABLE `clearinghouse` (
  `ClearinghouseNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `Description` varchar(255) DEFAULT '',
  `ExportPath` text DEFAULT NULL,
  `Payors` text DEFAULT NULL,
  `Eformat` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `ISA05` varchar(255) DEFAULT NULL,
  `SenderTIN` varchar(255) DEFAULT NULL,
  `ISA07` varchar(255) DEFAULT NULL,
  `ISA08` varchar(255) DEFAULT NULL,
  `ISA15` varchar(255) DEFAULT NULL,
  `Password` varchar(255) DEFAULT '',
  `ResponsePath` varchar(255) DEFAULT '',
  `CommBridge` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `ClientProgram` varchar(255) DEFAULT '',
  `LastBatchNumber` smallint(5) unsigned NOT NULL DEFAULT 0,
  `ModemPort` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `LoginID` varchar(255) DEFAULT '',
  `SenderName` varchar(255) DEFAULT NULL,
  `SenderTelephone` varchar(255) DEFAULT NULL,
  `GS03` varchar(255) DEFAULT NULL,
  `ISA02` varchar(10) NOT NULL,
  `ISA04` varchar(10) NOT NULL,
  `ISA16` varchar(2) NOT NULL,
  `SeparatorData` varchar(2) NOT NULL,
  `SeparatorSegment` varchar(2) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `HqClearinghouseNum` bigint(20) NOT NULL,
  `IsEraDownloadAllowed` tinyint(4) NOT NULL DEFAULT 2,
  `IsClaimExportAllowed` tinyint(4) NOT NULL DEFAULT 1,
  `IsAttachmentSendAllowed` tinyint(4) NOT NULL,
  `LocationID` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ClearinghouseNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `HqClearinghouseNum` (`HqClearinghouseNum`)
) ENGINE=MyISAM AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;