CREATE TABLE `clinic` (
  `ClinicNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `Description` varchar(255) DEFAULT '',
  `Address` varchar(255) DEFAULT '',
  `Address2` varchar(255) DEFAULT '',
  `City` varchar(255) DEFAULT '',
  `State` varchar(255) DEFAULT '',
  `Zip` varchar(255) DEFAULT '',
  `Phone` varchar(255) DEFAULT '',
  `BankNumber` varchar(255) DEFAULT '',
  `DefaultPlaceService` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `InsBillingProv` bigint(20) NOT NULL,
  `Fax` varchar(50) NOT NULL,
  `EmailAddressNum` bigint(20) NOT NULL,
  `DefaultProv` bigint(20) NOT NULL,
  `SmsContractDate` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SmsMonthlyLimit` double NOT NULL,
  `IsMedicalOnly` tinyint(4) NOT NULL,
  `BillingAddress` varchar(255) NOT NULL,
  `BillingAddress2` varchar(255) NOT NULL,
  `BillingCity` varchar(255) NOT NULL,
  `BillingState` varchar(255) NOT NULL,
  `BillingZip` varchar(255) NOT NULL,
  `PayToAddress` varchar(255) NOT NULL,
  `PayToAddress2` varchar(255) NOT NULL,
  `PayToCity` varchar(255) NOT NULL,
  `PayToState` varchar(255) NOT NULL,
  `PayToZip` varchar(255) NOT NULL,
  `UseBillAddrOnClaims` tinyint(4) NOT NULL,
  `Region` bigint(20) NOT NULL,
  `ItemOrder` int(11) NOT NULL,
  `IsInsVerifyExcluded` tinyint(4) NOT NULL,
  `Abbr` varchar(255) NOT NULL,
  `MedLabAccountNum` varchar(16) NOT NULL,
  `IsConfirmEnabled` tinyint(4) NOT NULL,
  `IsConfirmDefault` tinyint(4) NOT NULL,
  `IsNewPatApptExcluded` tinyint(4) NOT NULL,
  `IsHidden` tinyint(4) NOT NULL,
  `ExternalID` bigint(20) NOT NULL,
  `SchedNote` varchar(255) NOT NULL,
  `HasProcOnRx` tinyint(4) NOT NULL,
  `TimeZone` varchar(75) NOT NULL,
  `EmailAliasOverride` varchar(255) NOT NULL,
  PRIMARY KEY (`ClinicNum`),
  KEY `EmailAddressNum` (`EmailAddressNum`),
  KEY `DefaultProv` (`DefaultProv`),
  KEY `Region` (`Region`),
  KEY `ExternalID` (`ExternalID`),
  KEY `InsBillingProv` (`InsBillingProv`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;