CREATE TABLE `clockevent` (
  `ClockEventNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `EmployeeNum` bigint(20) NOT NULL,
  `TimeEntered1` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TimeDisplayed1` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ClockStatus` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `Note` text DEFAULT NULL,
  `TimeEntered2` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TimeDisplayed2` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `OTimeHours` time NOT NULL,
  `OTimeAuto` time NOT NULL,
  `Adjust` time NOT NULL,
  `AdjustAuto` time NOT NULL,
  `AdjustIsOverridden` tinyint(4) NOT NULL,
  `Rate2Hours` time NOT NULL,
  `Rate2Auto` time NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `Rate3Hours` time NOT NULL,
  `Rate3Auto` time NOT NULL,
  `IsWorkingHome` tinyint(4) NOT NULL,
  PRIMARY KEY (`ClockEventNum`),
  KEY `TimeDisplayed1` (`TimeDisplayed1`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `EmployeeNum` (`EmployeeNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;