CREATE TABLE `computerpref` (
  `ComputerPrefNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `ComputerName` varchar(64) NOT NULL,
  `GraphicsUseHardware` tinyint(1) NOT NULL DEFAULT 0,
  `GraphicsSimple` tinyint(1) NOT NULL DEFAULT 0,
  `SensorType` varchar(255) DEFAULT 'D',
  `SensorBinned` tinyint(4) NOT NULL,
  `SensorPort` int(11) DEFAULT 0,
  `SensorExposure` int(11) DEFAULT 1,
  `GraphicsDoubleBuffering` tinyint(4) NOT NULL,
  `PreferredPixelFormatNum` int(11) DEFAULT 0,
  `AtoZpath` varchar(255) DEFAULT NULL,
  `TaskKeepListHidden` tinyint(1) NOT NULL,
  `TaskDock` int(11) NOT NULL DEFAULT 0,
  `TaskX` int(11) NOT NULL DEFAULT 900,
  `TaskY` int(11) NOT NULL DEFAULT 625,
  `DirectXFormat` varchar(255) DEFAULT '',
  `ScanDocSelectSource` tinyint(4) NOT NULL,
  `ScanDocShowOptions` tinyint(4) NOT NULL,
  `ScanDocDuplex` tinyint(4) NOT NULL,
  `ScanDocGrayscale` tinyint(4) NOT NULL,
  `ScanDocResolution` int(11) NOT NULL,
  `ScanDocQuality` tinyint(3) unsigned NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `ApptViewNum` bigint(20) NOT NULL,
  `RecentApptView` tinyint(3) unsigned NOT NULL,
  `PatSelectSearchMode` tinyint(4) NOT NULL,
  `NoShowLanguage` tinyint(4) NOT NULL,
  `NoShowDecimal` tinyint(4) NOT NULL,
  `ComputerOS` varchar(255) NOT NULL,
  `HelpButtonXAdjustment` double NOT NULL,
  `GraphicsUseDirectX11` tinyint(4) NOT NULL DEFAULT 0,
  `Zoom` int(11) NOT NULL DEFAULT 0,
  `VideoRectangle` varchar(255) NOT NULL,
  PRIMARY KEY (`ComputerPrefNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `ApptViewNum` (`ApptViewNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;