CREATE TABLE `confirmationrequest` (
  `ConfirmationRequestNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `ClinicNum` bigint(20) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `ApptNum` bigint(20) NOT NULL,
  `DateTimeConfirmExpire` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ShortGUID` varchar(255) NOT NULL,
  `ConfirmCode` varchar(255) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeConfirmTransmit` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeRSVP` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `RSVPStatus` tinyint(4) NOT NULL,
  `ResponseDescript` text NOT NULL,
  `GuidMessageFromMobile` text NOT NULL,
  `ApptDateTime` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TSPrior` bigint(20) NOT NULL,
  `DoNotResend` tinyint(4) NOT NULL,
  `SendStatus` tinyint(4) NOT NULL,
  `ApptReminderRuleNum` bigint(20) NOT NULL,
  `MessageType` tinyint(4) NOT NULL,
  `MessageFk` bigint(20) NOT NULL,
  `DateTimeSent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  PRIMARY KEY (`ConfirmationRequestNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `PatNum` (`PatNum`),
  KEY `ApptNum` (`ApptNum`),
  KEY `TSPrior` (`TSPrior`),
  KEY `ApptReminderRuleNum` (`ApptReminderRuleNum`),
  KEY `MessageFk` (`MessageFk`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;