CREATE TABLE `creditcard` (
  `CreditCardNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `Address` varchar(255) DEFAULT NULL,
  `Zip` varchar(255) DEFAULT NULL,
  `XChargeToken` varchar(255) DEFAULT NULL,
  `CCNumberMasked` varchar(255) DEFAULT NULL,
  `CCExpiration` date NOT NULL DEFAULT '0001-01-01',
  `ItemOrder` int(11) NOT NULL,
  `ChargeAmt` double NOT NULL,
  `DateStart` date NOT NULL DEFAULT '0001-01-01',
  `DateStop` date NOT NULL DEFAULT '0001-01-01',
  `Note` varchar(255) NOT NULL,
  `PayPlanNum` bigint(20) NOT NULL,
  `PayConnectToken` varchar(255) NOT NULL,
  `PayConnectTokenExp` date NOT NULL DEFAULT '0001-01-01',
  `Procedures` text NOT NULL,
  `CCSource` tinyint(4) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `ExcludeProcSync` tinyint(4) NOT NULL,
  `PaySimpleToken` varchar(255) NOT NULL,
  `ChargeFrequency` varchar(150) NOT NULL,
  `CanChargeWhenNoBal` tinyint(4) NOT NULL,
  `PaymentType` bigint(20) NOT NULL,
  `IsRecurringActive` tinyint(4) NOT NULL,
  `Nickname` varchar(255) NOT NULL,
  PRIMARY KEY (`CreditCardNum`),
  KEY `PatNum` (`PatNum`),
  KEY `PayPlanNum` (`PayPlanNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `PaymentType` (`PaymentType`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;