CREATE TABLE `ehrlab` (
  `EhrLabNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `OrderControlCode` varchar(255) NOT NULL,
  `PlacerOrderNum` varchar(255) NOT NULL,
  `PlacerOrderNamespace` varchar(255) NOT NULL,
  `PlacerOrderUniversalID` varchar(255) NOT NULL,
  `PlacerOrderUniversalIDType` varchar(255) NOT NULL,
  `FillerOrderNum` varchar(255) NOT NULL,
  `FillerOrderNamespace` varchar(255) NOT NULL,
  `FillerOrderUniversalID` varchar(255) NOT NULL,
  `FillerOrderUniversalIDType` varchar(255) NOT NULL,
  `PlacerGroupNum` varchar(255) NOT NULL,
  `PlacerGroupNamespace` varchar(255) NOT NULL,
  `PlacerGroupUniversalID` varchar(255) NOT NULL,
  `PlacerGroupUniversalIDType` varchar(255) NOT NULL,
  `OrderingProviderID` varchar(255) NOT NULL,
  `OrderingProviderLName` varchar(255) NOT NULL,
  `OrderingProviderFName` varchar(255) NOT NULL,
  `OrderingProviderMiddleNames` varchar(255) NOT NULL,
  `OrderingProviderSuffix` varchar(255) NOT NULL,
  `OrderingProviderPrefix` varchar(255) NOT NULL,
  `OrderingProviderAssigningAuthorityNamespaceID` varchar(255) NOT NULL,
  `OrderingProviderAssigningAuthorityUniversalID` varchar(255) NOT NULL,
  `OrderingProviderAssigningAuthorityIDType` varchar(255) NOT NULL,
  `OrderingProviderNameTypeCode` varchar(255) NOT NULL,
  `OrderingProviderIdentifierTypeCode` varchar(255) NOT NULL,
  `SetIdOBR` bigint(20) NOT NULL,
  `UsiID` varchar(255) NOT NULL,
  `UsiText` varchar(255) NOT NULL,
  `UsiCodeSystemName` varchar(255) NOT NULL,
  `UsiIDAlt` varchar(255) NOT NULL,
  `UsiTextAlt` varchar(255) NOT NULL,
  `UsiCodeSystemNameAlt` varchar(255) NOT NULL,
  `UsiTextOriginal` varchar(255) NOT NULL,
  `ObservationDateTimeStart` varchar(255) NOT NULL,
  `ObservationDateTimeEnd` varchar(255) NOT NULL,
  `SpecimenActionCode` varchar(255) NOT NULL,
  `ResultDateTime` varchar(255) NOT NULL,
  `ResultStatus` varchar(255) NOT NULL,
  `ParentObservationID` varchar(255) NOT NULL,
  `ParentObservationText` varchar(255) NOT NULL,
  `ParentObservationCodeSystemName` varchar(255) NOT NULL,
  `ParentObservationIDAlt` varchar(255) NOT NULL,
  `ParentObservationTextAlt` varchar(255) NOT NULL,
  `ParentObservationCodeSystemNameAlt` varchar(255) NOT NULL,
  `ParentObservationTextOriginal` varchar(255) NOT NULL,
  `ParentObservationSubID` varchar(255) NOT NULL,
  `ParentPlacerOrderNum` varchar(255) NOT NULL,
  `ParentPlacerOrderNamespace` varchar(255) NOT NULL,
  `ParentPlacerOrderUniversalID` varchar(255) NOT NULL,
  `ParentPlacerOrderUniversalIDType` varchar(255) NOT NULL,
  `ParentFillerOrderNum` varchar(255) NOT NULL,
  `ParentFillerOrderNamespace` varchar(255) NOT NULL,
  `ParentFillerOrderUniversalID` varchar(255) NOT NULL,
  `ParentFillerOrderUniversalIDType` varchar(255) NOT NULL,
  `ListEhrLabResultsHandlingF` tinyint(4) NOT NULL,
  `ListEhrLabResultsHandlingN` tinyint(4) NOT NULL,
  `TQ1SetId` bigint(20) NOT NULL,
  `TQ1DateTimeStart` varchar(255) NOT NULL,
  `TQ1DateTimeEnd` varchar(255) NOT NULL,
  `IsCpoe` tinyint(4) NOT NULL,
  `OriginalPIDSegment` text NOT NULL,
  PRIMARY KEY (`EhrLabNum`),
  KEY `PatNum` (`PatNum`),
  KEY `SetIdOBR` (`SetIdOBR`),
  KEY `TQ1SetId` (`TQ1SetId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;