CREATE TABLE `emailmessage` (
  `EmailMessageNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `ToAddress` text DEFAULT NULL,
  `FromAddress` text DEFAULT NULL,
  `Subject` text DEFAULT NULL,
  `BodyText` longtext NOT NULL,
  `MsgDateTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `SentOrReceived` tinyint(3) unsigned NOT NULL,
  `RecipientAddress` varchar(255) NOT NULL,
  `RawEmailIn` longtext NOT NULL,
  `ProvNumWebMail` bigint(20) NOT NULL,
  `PatNumSubj` bigint(20) NOT NULL,
  `CcAddress` text NOT NULL,
  `BccAddress` text NOT NULL,
  `HideIn` tinyint(4) NOT NULL,
  `AptNum` bigint(20) NOT NULL,
  `UserNum` bigint(20) NOT NULL,
  `HtmlType` tinyint(4) NOT NULL,
  `SecDateTEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `MsgType` varchar(255) NOT NULL,
  `FailReason` varchar(255) NOT NULL,
  PRIMARY KEY (`EmailMessageNum`),
  KEY `PatNum` (`PatNum`),
  KEY `ProvNumWebMail` (`ProvNumWebMail`),
  KEY `PatNumSubj` (`PatNumSubj`),
  KEY `AptNum` (`AptNum`),
  KEY `UserNum` (`UserNum`),
  KEY `MsgBoxCompound` (`MsgDateTime`,`SentOrReceived`),
  KEY `SentOrReceived` (`SentOrReceived`),
  KEY `MsgHistoricAddresses` (`SentOrReceived`,`RecipientAddress`(50),`FromAddress`(50)),
  KEY `SecDateTEntry` (`SecDateTEntry`),
  KEY `SecDateTEdit` (`SecDateTEdit`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;