CREATE TABLE `etrans` (
  `EtransNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `DateTimeTrans` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ClearingHouseNum` bigint(20) NOT NULL,
  `Etype` tinyint(3) unsigned NOT NULL,
  `ClaimNum` bigint(20) NOT NULL,
  `OfficeSequenceNumber` int(11) NOT NULL,
  `CarrierTransCounter` int(11) NOT NULL,
  `CarrierTransCounter2` int(11) NOT NULL,
  `CarrierNum` bigint(20) NOT NULL,
  `CarrierNum2` bigint(20) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `BatchNumber` int(11) NOT NULL,
  `AckCode` varchar(255) DEFAULT NULL,
  `TransSetNum` int(11) NOT NULL,
  `Note` text DEFAULT NULL,
  `EtransMessageTextNum` bigint(20) NOT NULL,
  `AckEtransNum` bigint(20) NOT NULL,
  `PlanNum` bigint(20) NOT NULL,
  `InsSubNum` bigint(20) NOT NULL,
  `TranSetId835` varchar(255) NOT NULL,
  `CarrierNameRaw` varchar(60) NOT NULL,
  `PatientNameRaw` varchar(133) NOT NULL,
  `UserNum` bigint(20) NOT NULL,
  PRIMARY KEY (`EtransNum`),
  KEY `ClaimNum` (`ClaimNum`),
  KEY `CarrierNum` (`CarrierNum`),
  KEY `CarrierNum2` (`CarrierNum2`),
  KEY `PlanNum` (`PlanNum`),
  KEY `InsSubNum` (`InsSubNum`),
  KEY `EtransMessageTextNum` (`EtransMessageTextNum`),
  KEY `UserNum` (`UserNum`),
  KEY `EtransTypeAndDate` (`Etype`,`DateTimeTrans`),
  KEY `ClearingHouseNum` (`ClearingHouseNum`),
  KEY `PatNum` (`PatNum`),
  KEY `AckEtransNum` (`AckEtransNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;