CREATE TABLE `histappointment` (
  `HistApptNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `HistUserNum` bigint(20) NOT NULL,
  `HistDateTStamp` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `HistApptAction` tinyint(4) NOT NULL,
  `ApptSource` tinyint(4) NOT NULL,
  `AptNum` bigint(20) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `AptStatus` tinyint(4) NOT NULL,
  `Pattern` varchar(255) NOT NULL,
  `Confirmed` bigint(20) NOT NULL,
  `TimeLocked` tinyint(4) NOT NULL,
  `Op` bigint(20) NOT NULL,
  `Note` text NOT NULL,
  `ProvNum` bigint(20) NOT NULL,
  `ProvHyg` bigint(20) NOT NULL,
  `AptDateTime` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `NextAptNum` bigint(20) NOT NULL,
  `UnschedStatus` bigint(20) NOT NULL,
  `IsNewPatient` tinyint(4) NOT NULL,
  `ProcDescript` varchar(255) NOT NULL,
  `Assistant` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `IsHygiene` tinyint(4) NOT NULL,
  `DateTStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `DateTimeArrived` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeSeated` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeDismissed` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `InsPlan1` bigint(20) NOT NULL,
  `InsPlan2` bigint(20) NOT NULL,
  `DateTimeAskedToArrive` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ProcsColored` text NOT NULL,
  `ColorOverride` int(11) NOT NULL,
  `AppointmentTypeNum` bigint(20) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateTEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `Priority` tinyint(4) NOT NULL,
  `ProvBarText` varchar(60) NOT NULL,
  `PatternSecondary` varchar(255) NOT NULL,
  `SecurityHash` varchar(255) NOT NULL,
  PRIMARY KEY (`HistApptNum`),
  KEY `HistUserNum` (`HistUserNum`),
  KEY `AptNum` (`AptNum`),
  KEY `PatNum` (`PatNum`),
  KEY `Confirmed` (`Confirmed`),
  KEY `Op` (`Op`),
  KEY `ProvNum` (`ProvNum`),
  KEY `ProvHyg` (`ProvHyg`),
  KEY `NextAptNum` (`NextAptNum`),
  KEY `UnschedStatus` (`UnschedStatus`),
  KEY `Assistant` (`Assistant`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `InsPlan1` (`InsPlan1`),
  KEY `InsPlan2` (`InsPlan2`),
  KEY `AppointmentTypeNum` (`AppointmentTypeNum`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;