CREATE TABLE `hl7def` (
  `HL7DefNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `Description` varchar(255) NOT NULL,
  `ModeTx` tinyint(4) NOT NULL,
  `IncomingFolder` varchar(255) NOT NULL,
  `OutgoingFolder` varchar(255) NOT NULL,
  `IncomingPort` varchar(255) NOT NULL,
  `OutgoingIpPort` varchar(255) NOT NULL,
  `FieldSeparator` varchar(5) NOT NULL,
  `ComponentSeparator` varchar(5) NOT NULL,
  `SubcomponentSeparator` varchar(5) NOT NULL,
  `RepetitionSeparator` varchar(5) NOT NULL,
  `EscapeCharacter` varchar(5) NOT NULL,
  `IsInternal` tinyint(4) NOT NULL,
  `InternalType` varchar(255) NOT NULL,
  `InternalTypeVersion` varchar(50) NOT NULL,
  `IsEnabled` tinyint(4) NOT NULL,
  `Note` text NOT NULL,
  `HL7Server` varchar(255) NOT NULL,
  `HL7ServiceName` varchar(255) NOT NULL,
  `ShowDemographics` tinyint(4) NOT NULL,
  `ShowAppts` tinyint(4) NOT NULL,
  `ShowAccount` tinyint(4) NOT NULL,
  `IsQuadAsToothNum` tinyint(4) NOT NULL,
  `LabResultImageCat` bigint(20) NOT NULL,
  `SftpUsername` varchar(255) NOT NULL,
  `SftpPassword` varchar(255) NOT NULL,
  `SftpInSocket` varchar(255) NOT NULL,
  `HasLongDCodes` tinyint(4) NOT NULL,
  `IsProcApptEnforced` tinyint(4) NOT NULL,
  PRIMARY KEY (`HL7DefNum`),
  KEY `LabResultImageCat` (`LabResultImageCat`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;