CREATE TABLE `insplan` (
  `PlanNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `GroupName` varchar(50) DEFAULT '',
  `GroupNum` varchar(25) DEFAULT NULL,
  `PlanNote` text NOT NULL,
  `FeeSched` bigint(20) NOT NULL,
  `PlanType` char(1) DEFAULT '',
  `ClaimFormNum` bigint(20) NOT NULL,
  `UseAltCode` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `ClaimsUseUCR` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `CopayFeeSched` bigint(20) NOT NULL,
  `EmployerNum` bigint(20) NOT NULL,
  `CarrierNum` bigint(20) NOT NULL,
  `AllowedFeeSched` bigint(20) NOT NULL,
  `TrojanID` varchar(100) DEFAULT '',
  `DivisionNo` varchar(255) DEFAULT '',
  `IsMedical` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `FilingCode` bigint(20) NOT NULL,
  `DentaideCardSequence` tinyint(3) unsigned NOT NULL,
  `ShowBaseUnits` tinyint(1) NOT NULL,
  `CodeSubstNone` tinyint(1) NOT NULL,
  `IsHidden` tinyint(4) NOT NULL,
  `MonthRenew` tinyint(4) NOT NULL,
  `FilingCodeSubtype` bigint(20) NOT NULL,
  `CanadianPlanFlag` varchar(5) NOT NULL,
  `CanadianDiagnosticCode` varchar(255) NOT NULL,
  `CanadianInstitutionCode` varchar(255) NOT NULL,
  `RxBIN` varchar(255) NOT NULL,
  `CobRule` tinyint(4) NOT NULL,
  `SopCode` varchar(255) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateEntry` date NOT NULL DEFAULT '0001-01-01',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `HideFromVerifyList` tinyint(4) NOT NULL,
  `OrthoType` tinyint(4) NOT NULL,
  `OrthoAutoProcFreq` tinyint(4) NOT NULL,
  `OrthoAutoProcCodeNumOverride` bigint(20) NOT NULL,
  `OrthoAutoFeeBilled` double NOT NULL,
  `OrthoAutoClaimDaysWait` int(11) NOT NULL,
  `BillingType` bigint(20) NOT NULL,
  `HasPpoSubstWriteoffs` tinyint(4) NOT NULL,
  `ExclusionFeeRule` tinyint(4) NOT NULL,
  `ManualFeeSchedNum` bigint(20) NOT NULL DEFAULT 0,
  `IsBlueBookEnabled` tinyint(4) NOT NULL DEFAULT 1,
  `InsPlansZeroWriteOffsOnAnnualMaxOverride` tinyint(4) NOT NULL,
  `InsPlansZeroWriteOffsOnFreqOrAgingOverride` tinyint(4) NOT NULL,
  `PerVisitPatAmount` double NOT NULL,
  `PerVisitInsAmount` double NOT NULL,
  PRIMARY KEY (`PlanNum`),
  KEY `CarrierNum` (`CarrierNum`),
  KEY `FilingCodeSubtype` (`FilingCodeSubtype`),
  KEY `TrojanID` (`TrojanID`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`),
  KEY `CarrierNumPlanNum` (`CarrierNum`,`PlanNum`),
  KEY `OrthoAutoProcCodeNumOverride` (`OrthoAutoProcCodeNumOverride`),
  KEY `BillingType` (`BillingType`),
  KEY `FeeSched` (`FeeSched`),
  KEY `CopayFeeSched` (`CopayFeeSched`),
  KEY `ManualFeeSchedNum` (`ManualFeeSchedNum`),
  KEY `AllowedFeeSched` (`AllowedFeeSched`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;