CREATE TABLE `medlab` (
  `MedLabNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `SendingApp` varchar(255) NOT NULL,
  `SendingFacility` varchar(255) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `ProvNum` bigint(20) NOT NULL,
  `PatIDLab` varchar(255) NOT NULL,
  `PatIDAlt` varchar(255) NOT NULL,
  `PatAge` varchar(255) NOT NULL,
  `PatAccountNum` varchar(255) NOT NULL,
  `PatFasting` tinyint(4) NOT NULL,
  `SpecimenID` varchar(255) NOT NULL,
  `SpecimenIDFiller` varchar(255) NOT NULL,
  `ObsTestID` varchar(255) NOT NULL,
  `ObsTestDescript` varchar(255) NOT NULL,
  `ObsTestLoinc` varchar(255) NOT NULL,
  `ObsTestLoincText` varchar(255) NOT NULL,
  `DateTimeCollected` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TotalVolume` varchar(255) NOT NULL,
  `ActionCode` varchar(255) NOT NULL,
  `ClinicalInfo` varchar(255) NOT NULL,
  `DateTimeEntered` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `OrderingProvNPI` varchar(255) NOT NULL,
  `OrderingProvLocalID` varchar(255) NOT NULL,
  `OrderingProvLName` varchar(255) NOT NULL,
  `OrderingProvFName` varchar(255) NOT NULL,
  `SpecimenIDAlt` varchar(255) NOT NULL,
  `DateTimeReported` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ResultStatus` varchar(255) NOT NULL,
  `ParentObsID` varchar(255) NOT NULL,
  `ParentObsTestID` varchar(255) NOT NULL,
  `NotePat` text NOT NULL,
  `NoteLab` text NOT NULL,
  `FileName` varchar(255) NOT NULL,
  `OriginalPIDSegment` text NOT NULL,
  PRIMARY KEY (`MedLabNum`),
  KEY `PatNum` (`PatNum`),
  KEY `ProvNum` (`ProvNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;