CREATE TABLE `medlabresult` (
  `MedLabResultNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `MedLabNum` bigint(20) NOT NULL,
  `ObsID` varchar(255) NOT NULL,
  `ObsText` varchar(255) NOT NULL,
  `ObsLoinc` varchar(255) NOT NULL,
  `ObsLoincText` varchar(255) NOT NULL,
  `ObsIDSub` varchar(255) NOT NULL,
  `ObsValue` text NOT NULL,
  `ObsSubType` varchar(255) NOT NULL,
  `ObsUnits` varchar(255) NOT NULL,
  `ReferenceRange` varchar(255) NOT NULL,
  `AbnormalFlag` varchar(255) NOT NULL,
  `ResultStatus` varchar(255) NOT NULL,
  `DateTimeObs` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `FacilityID` varchar(255) NOT NULL,
  `DocNum` bigint(20) NOT NULL,
  `Note` text NOT NULL,
  PRIMARY KEY (`MedLabResultNum`),
  KEY `MedLabNum` (`MedLabNum`),
  KEY `DocNum` (`DocNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;