CREATE TABLE `msgtopaysent` (
  `MsgToPaySentNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `SendStatus` tinyint(4) NOT NULL,
  `Source` tinyint(4) NOT NULL,
  `MessageType` tinyint(4) NOT NULL,
  `MessageFk` bigint(20) NOT NULL,
  `Subject` text NOT NULL,
  `Message` text NOT NULL,
  `EmailType` tinyint(4) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeSent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ResponseDescript` text NOT NULL,
  `ApptReminderRuleNum` bigint(20) NOT NULL,
  `ShortGUID` varchar(255) NOT NULL,
  `DateTimeSendFailed` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  PRIMARY KEY (`MsgToPaySentNum`),
  KEY `PatNum` (`PatNum`),
  KEY `DateTimeSent` (`DateTimeSent`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `MessageFk` (`MessageFk`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;