CREATE TABLE `orthocase` (
  `OrthoCaseNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `ProvNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `Fee` double NOT NULL,
  `FeeInsPrimary` double NOT NULL,
  `FeePat` double NOT NULL,
  `BandingDate` date NOT NULL DEFAULT '0001-01-01',
  `DebondDate` date NOT NULL DEFAULT '0001-01-01',
  `DebondDateExpected` date NOT NULL DEFAULT '0001-01-01',
  `IsTransfer` tinyint(4) NOT NULL,
  `OrthoType` bigint(20) NOT NULL,
  `SecDateTEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `IsActive` tinyint(4) NOT NULL,
  `FeeInsSecondary` double NOT NULL,
  PRIMARY KEY (`OrthoCaseNum`),
  KEY `PatNum` (`PatNum`),
  KEY `ProvNum` (`ProvNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `OrthoType` (`OrthoType`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;