CREATE TABLE `patientportalinvite` (
  `PatientPortalInviteNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `ApptNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TSPrior` bigint(20) NOT NULL,
  `SendStatus` tinyint(4) NOT NULL,
  `MessageFk` bigint(20) NOT NULL,
  `ResponseDescript` text NOT NULL,
  `MessageType` tinyint(4) NOT NULL,
  `DateTimeSent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ApptReminderRuleNum` bigint(20) NOT NULL,
  `ApptDateTime` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  PRIMARY KEY (`PatientPortalInviteNum`),
  KEY `PatNum` (`PatNum`),
  KEY `AptNum` (`ApptNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `EmailMessageNum` (`MessageFk`),
  KEY `MessageFk` (`MessageFk`),
  KEY `ApptReminderRuleNum` (`ApptReminderRuleNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;