CREATE TABLE `payconnectresponseweb` (
  `PayConnectResponseWebNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `PayNum` bigint(20) NOT NULL,
  `AccountToken` varchar(255) NOT NULL,
  `PaymentToken` varchar(255) NOT NULL,
  `ProcessingStatus` varchar(255) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimePending` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeCompleted` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeExpired` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeLastError` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `LastResponseStr` text NOT NULL,
  `CCSource` tinyint(4) NOT NULL,
  `Amount` double NOT NULL,
  `PayNote` varchar(255) NOT NULL,
  `IsTokenSaved` tinyint(4) NOT NULL,
  `PayToken` varchar(255) NOT NULL,
  `ExpDateToken` varchar(255) NOT NULL,
  `RefNumber` varchar(255) NOT NULL,
  `TransType` varchar(255) NOT NULL,
  `EmailResponse` varchar(255) NOT NULL,
  `LogGuid` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`PayConnectResponseWebNum`),
  KEY `PatNum` (`PatNum`),
  KEY `PayNum` (`PayNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;