CREATE TABLE `payment` (
  `PayNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PayType` bigint(20) NOT NULL,
  `PayDate` date NOT NULL DEFAULT '0000-00-00',
  `PayAmt` double NOT NULL DEFAULT 0,
  `CheckNum` varchar(25) DEFAULT '',
  `BankBranch` varchar(25) DEFAULT '',
  `PayNote` text NOT NULL,
  `IsSplit` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `PatNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `DateEntry` date NOT NULL DEFAULT '0001-01-01',
  `DepositNum` bigint(20) NOT NULL,
  `Receipt` text NOT NULL,
  `IsRecurringCC` tinyint(4) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `PaymentSource` tinyint(4) NOT NULL,
  `ProcessStatus` tinyint(4) NOT NULL,
  `RecurringChargeDate` date NOT NULL DEFAULT '0001-01-01',
  `ExternalId` varchar(255) NOT NULL,
  `PaymentStatus` tinyint(4) NOT NULL,
  `IsCcCompleted` tinyint(4) NOT NULL,
  `MerchantFee` double NOT NULL,
  PRIMARY KEY (`PayNum`),
  KEY `indexPatNum` (`PatNum`),
  KEY `DepositNum` (`DepositNum`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `PayType` (`PayType`),
  KEY `ProcessStatus` (`ProcessStatus`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;