CREATE TABLE `payplan` (
  `PayPlanNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `Guarantor` bigint(20) NOT NULL,
  `PayPlanDate` date NOT NULL DEFAULT '0000-00-00',
  `APR` double NOT NULL DEFAULT 0,
  `Note` text DEFAULT NULL,
  `PlanNum` bigint(20) NOT NULL,
  `CompletedAmt` double NOT NULL,
  `InsSubNum` bigint(20) NOT NULL,
  `PaySchedule` tinyint(4) NOT NULL,
  `NumberOfPayments` int(11) NOT NULL,
  `PayAmt` double NOT NULL,
  `DownPayment` double NOT NULL,
  `IsClosed` tinyint(4) NOT NULL,
  `Signature` text NOT NULL,
  `SigIsTopaz` tinyint(4) NOT NULL,
  `PlanCategory` bigint(20) NOT NULL,
  `IsDynamic` tinyint(4) NOT NULL,
  `ChargeFrequency` tinyint(4) NOT NULL,
  `DatePayPlanStart` date NOT NULL DEFAULT '0001-01-01',
  `IsLocked` tinyint(4) NOT NULL,
  `DateInterestStart` date NOT NULL DEFAULT '0001-01-01',
  `DynamicPayPlanTPOption` tinyint(4) NOT NULL,
  `MobileAppDeviceNum` bigint(20) NOT NULL,
  `SecurityHash` varchar(255) NOT NULL,
  PRIMARY KEY (`PayPlanNum`),
  KEY `InsSubNum` (`InsSubNum`),
  KEY `PlanCategory` (`PlanCategory`),
  KEY `PatNum` (`PatNum`),
  KEY `Guarantor` (`Guarantor`),
  KEY `PlanNum` (`PlanNum`),
  KEY `MobileAppDeviceNum` (`MobileAppDeviceNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;