CREATE TABLE `payplancharge` (
  `PayPlanChargeNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PayPlanNum` bigint(20) NOT NULL,
  `Guarantor` bigint(20) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `ChargeDate` date NOT NULL DEFAULT '0001-01-01',
  `Principal` double NOT NULL DEFAULT 0,
  `Interest` double NOT NULL DEFAULT 0,
  `Note` text DEFAULT NULL,
  `ProvNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `ChargeType` tinyint(4) NOT NULL,
  `ProcNum` bigint(20) NOT NULL,
  `SecDateTEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `StatementNum` bigint(20) NOT NULL,
  `FKey` bigint(20) NOT NULL,
  `LinkType` tinyint(4) NOT NULL,
  `IsOffset` tinyint(4) NOT NULL,
  PRIMARY KEY (`PayPlanChargeNum`),
  KEY `indexPatNum` (`PatNum`),
  KEY `indexGuarantor` (`Guarantor`),
  KEY `indexPayPlanNum` (`PayPlanNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `ProcNum` (`ProcNum`),
  KEY `StatementNum` (`StatementNum`),
  KEY `FKey` (`FKey`),
  KEY `SecDateTEditPN` (`SecDateTEdit`,`PatNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;