CREATE TABLE `procedurecode` (
  `CodeNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `ProcCode` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `Descript` varchar(255) DEFAULT '',
  `AbbrDesc` varchar(50) DEFAULT '',
  `ProcTime` varchar(24) DEFAULT '',
  `ProcCat` bigint(20) NOT NULL,
  `TreatArea` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `NoBillIns` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `IsProsth` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `DefaultNote` text DEFAULT NULL,
  `IsHygiene` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `GTypeNum` smallint(5) unsigned NOT NULL DEFAULT 0,
  `AlternateCode1` varchar(15) DEFAULT '',
  `MedicalCode` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '',
  `IsTaxed` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `PaintType` tinyint(4) NOT NULL DEFAULT 0,
  `GraphicColor` int(11) NOT NULL,
  `LaymanTerm` varchar(255) DEFAULT '',
  `IsCanadianLab` tinyint(3) unsigned NOT NULL,
  `PreExisting` tinyint(1) NOT NULL DEFAULT 0,
  `BaseUnits` int(11) NOT NULL,
  `SubstitutionCode` varchar(25) DEFAULT NULL,
  `SubstOnlyIf` int(11) NOT NULL,
  `DateTStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `IsMultiVisit` tinyint(4) NOT NULL,
  `DrugNDC` varchar(255) NOT NULL,
  `RevenueCodeDefault` varchar(255) NOT NULL,
  `ProvNumDefault` bigint(20) NOT NULL,
  `CanadaTimeUnits` double NOT NULL,
  `IsRadiology` tinyint(4) NOT NULL,
  `DefaultClaimNote` text NOT NULL,
  `DefaultTPNote` text NOT NULL,
  `BypassGlobalLock` tinyint(4) NOT NULL,
  `TaxCode` varchar(16) NOT NULL,
  `PaintText` varchar(255) NOT NULL,
  `AreaAlsoToothRange` tinyint(4) NOT NULL,
  `DiagnosticCodes` varchar(255) NOT NULL,
  PRIMARY KEY (`CodeNum`),
  KEY `ProcCode` (`ProcCode`),
  KEY `ProvNumDefault` (`ProvNumDefault`)
) ENGINE=MyISAM AUTO_INCREMENT=45 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;