CREATE TABLE `procedurelog` (
  `ProcNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `AptNum` bigint(20) NOT NULL,
  `OldCode` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `ProcDate` date NOT NULL DEFAULT '0001-01-01',
  `ProcFee` double NOT NULL DEFAULT 0,
  `Surf` varchar(10) DEFAULT '',
  `ToothNum` varchar(2) DEFAULT '',
  `ToothRange` varchar(100) DEFAULT '',
  `Priority` bigint(20) NOT NULL,
  `ProcStatus` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `ProvNum` bigint(20) NOT NULL,
  `Dx` bigint(20) NOT NULL,
  `PlannedAptNum` bigint(20) NOT NULL,
  `PlaceService` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `Prosthesis` char(1) DEFAULT '',
  `DateOriginalProsth` date NOT NULL DEFAULT '0001-01-01',
  `ClaimNote` varchar(80) DEFAULT '',
  `DateEntryC` date NOT NULL DEFAULT '0001-01-01',
  `ClinicNum` bigint(20) NOT NULL,
  `MedicalCode` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '',
  `DiagnosticCode` varchar(255) DEFAULT '',
  `IsPrincDiag` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `ProcNumLab` bigint(20) NOT NULL,
  `BillingTypeOne` bigint(20) NOT NULL,
  `BillingTypeTwo` bigint(20) NOT NULL,
  `CodeNum` bigint(20) NOT NULL,
  `CodeMod1` char(2) DEFAULT NULL,
  `CodeMod2` char(2) DEFAULT NULL,
  `CodeMod3` char(2) DEFAULT NULL,
  `CodeMod4` char(2) DEFAULT NULL,
  `RevCode` varchar(45) DEFAULT NULL,
  `UnitQty` int(11) NOT NULL,
  `BaseUnits` int(11) NOT NULL,
  `StartTime` int(11) NOT NULL,
  `StopTime` int(11) NOT NULL,
  `DateTP` date NOT NULL,
  `SiteNum` bigint(20) NOT NULL,
  `HideGraphics` tinyint(4) NOT NULL,
  `CanadianTypeCodes` varchar(20) NOT NULL,
  `ProcTime` time NOT NULL,
  `ProcTimeEnd` time NOT NULL,
  `DateTStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `Prognosis` bigint(20) NOT NULL,
  `DrugUnit` tinyint(4) NOT NULL,
  `DrugQty` float NOT NULL,
  `UnitQtyType` tinyint(4) NOT NULL,
  `StatementNum` bigint(20) NOT NULL,
  `IsLocked` tinyint(4) NOT NULL,
  `BillingNote` varchar(255) NOT NULL,
  `RepeatChargeNum` bigint(20) NOT NULL,
  `SnomedBodySite` varchar(255) NOT NULL,
  `DiagnosticCode2` varchar(255) NOT NULL,
  `DiagnosticCode3` varchar(255) NOT NULL,
  `DiagnosticCode4` varchar(255) NOT NULL,
  `ProvOrderOverride` bigint(20) NOT NULL,
  `Discount` double NOT NULL,
  `IsDateProsthEst` tinyint(4) NOT NULL,
  `IcdVersion` tinyint(3) unsigned NOT NULL,
  `IsCpoe` tinyint(4) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateComplete` date NOT NULL DEFAULT '0001-01-01',
  `OrderingReferralNum` bigint(20) NOT NULL,
  `TaxAmt` double NOT NULL,
  `Urgency` tinyint(4) NOT NULL,
  `DiscountPlanAmt` double NOT NULL,
  PRIMARY KEY (`ProcNum`),
  KEY `CodeNum` (`CodeNum`),
  KEY `PlannedAptNum` (`PlannedAptNum`),
  KEY `BillingTypeOne` (`BillingTypeOne`),
  KEY `BillingTypeTwo` (`BillingTypeTwo`),
  KEY `Prognosis` (`Prognosis`),
  KEY `procedurelog_ProcNumLab` (`ProcNumLab`),
  KEY `StatementNum` (`StatementNum`),
  KEY `RepeatChargeNum` (`RepeatChargeNum`),
  KEY `ProvOrderOverride` (`ProvOrderOverride`),
  KEY `indexPNPSCN` (`PatNum`,`ProcStatus`,`ClinicNum`),
  KEY `indexPNPD` (`ProvNum`,`ProcDate`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `indexAgingCovering` (`PatNum`,`ProcStatus`,`ProcFee`,`UnitQty`,`BaseUnits`,`ProcDate`),
  KEY `OrderingReferralNum` (`OrderingReferralNum`),
  KEY `PatStatusCodeDate` (`PatNum`,`ProcStatus`,`CodeNum`,`ProcDate`),
  KEY `DateComplete` (`DateComplete`),
  KEY `RadiologyProcs` (`AptNum`,`CodeNum`,`ProcStatus`,`IsCpoe`,`ProvNum`),
  KEY `Priority` (`Priority`),
  KEY `DateClinicStatus` (`ProcDate`,`ClinicNum`,`ProcStatus`),
  KEY `DateTStampPN` (`DateTStamp`,`PatNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;