CREATE TABLE `provider` (
  `ProvNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `Abbr` varchar(255) DEFAULT NULL,
  `ItemOrder` smallint(5) unsigned NOT NULL DEFAULT 0,
  `LName` varchar(100) DEFAULT '',
  `FName` varchar(100) DEFAULT '',
  `MI` varchar(100) DEFAULT '',
  `Suffix` varchar(100) DEFAULT '',
  `FeeSched` bigint(20) NOT NULL,
  `Specialty` bigint(20) NOT NULL,
  `SSN` varchar(12) DEFAULT '',
  `StateLicense` varchar(15) DEFAULT '',
  `DEANum` varchar(15) DEFAULT '',
  `IsSecondary` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `ProvColor` int(11) NOT NULL DEFAULT 0,
  `IsHidden` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `UsingTIN` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `BlueCrossID` varchar(25) DEFAULT '',
  `SigOnFile` tinyint(1) unsigned NOT NULL DEFAULT 1,
  `MedicaidID` varchar(20) DEFAULT '',
  `OutlineColor` int(11) NOT NULL DEFAULT 0,
  `SchoolClassNum` bigint(20) NOT NULL,
  `NationalProvID` varchar(255) DEFAULT '',
  `CanadianOfficeNum` varchar(100) DEFAULT '',
  `DateTStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `AnesthProvType` bigint(20) NOT NULL,
  `TaxonomyCodeOverride` varchar(255) NOT NULL,
  `IsCDAnet` tinyint(4) NOT NULL,
  `EcwID` varchar(255) NOT NULL,
  `StateRxID` varchar(255) NOT NULL,
  `IsNotPerson` tinyint(4) NOT NULL,
  `StateWhereLicensed` varchar(50) NOT NULL,
  `EmailAddressNum` bigint(20) NOT NULL,
  `IsInstructor` tinyint(4) NOT NULL,
  `EhrMuStage` int(11) NOT NULL,
  `ProvNumBillingOverride` bigint(20) NOT NULL,
  `CustomID` varchar(255) NOT NULL,
  `ProvStatus` tinyint(4) NOT NULL,
  `IsHiddenReport` tinyint(4) NOT NULL,
  `IsErxEnabled` tinyint(4) NOT NULL,
  `Birthdate` date NOT NULL DEFAULT '0001-01-01',
  `SchedNote` varchar(255) NOT NULL,
  `WebSchedDescript` varchar(500) NOT NULL,
  `WebSchedImageLocation` varchar(255) NOT NULL,
  `HourlyProdGoalAmt` double NOT NULL,
  `DateTerm` date NOT NULL DEFAULT '0001-01-01',
  `PreferredName` varchar(100) NOT NULL,
  PRIMARY KEY (`ProvNum`),
  KEY `EmailAddressNum` (`EmailAddressNum`),
  KEY `ProvNumBillingOverride` (`ProvNumBillingOverride`),
  KEY `FeeSched` (`FeeSched`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;