CREATE TABLE `smsfrommobile` (
  `SmsFromMobileNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `CommlogNum` bigint(20) NOT NULL,
  `MsgText` text NOT NULL,
  `DateTimeReceived` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SmsPhoneNumber` varchar(255) NOT NULL,
  `MobilePhoneNumber` varchar(255) NOT NULL,
  `MsgPart` int(11) NOT NULL,
  `MsgTotal` int(11) NOT NULL,
  `MsgRefID` varchar(255) NOT NULL,
  `SmsStatus` tinyint(4) NOT NULL,
  `Flags` varchar(255) NOT NULL,
  `IsHidden` tinyint(4) NOT NULL,
  `MatchCount` int(11) NOT NULL,
  `GuidMessage` varchar(255) NOT NULL,
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`SmsFromMobileNum`),
  KEY `PatNum` (`PatNum`),
  KEY `CommlogNum` (`CommlogNum`),
  KEY `SecDateTEdit` (`SecDateTEdit`),
  KEY `StatusHiddenClinic` (`SmsStatus`,`IsHidden`,`ClinicNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;