CREATE TABLE `smstomobile` (
  `SmsToMobileNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `GuidMessage` varchar(255) NOT NULL,
  `GuidBatch` varchar(255) NOT NULL,
  `SmsPhoneNumber` varchar(255) NOT NULL,
  `MobilePhoneNumber` varchar(255) NOT NULL,
  `IsTimeSensitive` tinyint(4) NOT NULL,
  `MsgType` tinyint(4) NOT NULL,
  `MsgText` text NOT NULL,
  `SmsStatus` tinyint(4) NOT NULL,
  `MsgParts` int(11) NOT NULL,
  `MsgChargeUSD` float NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `CustErrorText` varchar(255) NOT NULL,
  `DateTimeSent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeTerminated` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `IsHidden` tinyint(4) NOT NULL,
  `MsgDiscountUSD` float NOT NULL,
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`SmsToMobileNum`),
  KEY `PatNum` (`PatNum`),
  KEY `ClinicDTSent` (`ClinicNum`,`DateTimeSent`),
  KEY `SecDateTEdit` (`SecDateTEdit`),
  KEY `GuidMessage` (`GuidMessage`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;