CREATE TABLE `statement` (
  `StatementNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `DateSent` date NOT NULL,
  `DateRangeFrom` date NOT NULL,
  `DateRangeTo` date NOT NULL,
  `Note` text DEFAULT NULL,
  `NoteBold` text DEFAULT NULL,
  `Mode_` tinyint(3) unsigned NOT NULL,
  `HidePayment` tinyint(1) NOT NULL,
  `SinglePatient` tinyint(1) NOT NULL,
  `Intermingled` tinyint(1) NOT NULL,
  `IsSent` tinyint(1) NOT NULL,
  `DocNum` bigint(20) NOT NULL,
  `DateTStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `IsReceipt` tinyint(4) NOT NULL,
  `IsInvoice` tinyint(4) NOT NULL,
  `IsInvoiceCopy` tinyint(4) NOT NULL,
  `EmailSubject` varchar(255) NOT NULL,
  `EmailBody` mediumtext NOT NULL,
  `SuperFamily` bigint(20) NOT NULL,
  `IsBalValid` tinyint(4) NOT NULL,
  `InsEst` double NOT NULL,
  `BalTotal` double NOT NULL,
  `StatementType` varchar(50) NOT NULL,
  `ShortGUID` varchar(30) NOT NULL,
  `StatementShortURL` varchar(50) NOT NULL,
  `StatementURL` varchar(255) NOT NULL,
  `SmsSendStatus` tinyint(4) NOT NULL,
  `LimitedCustomFamily` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`StatementNum`),
  KEY `PatNum` (`PatNum`),
  KEY `DocNum` (`DocNum`),
  KEY `SuperFamModeDateSent` (`SuperFamily`,`Mode_`,`DateSent`),
  KEY `ShortGUID` (`ShortGUID`),
  KEY `IsSent` (`IsSent`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;