CREATE TABLE `taskhist` (
  `TaskHistNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `UserNumHist` bigint(20) NOT NULL,
  `DateTStamp` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `IsNoteChange` tinyint(4) NOT NULL,
  `TaskNum` bigint(20) NOT NULL,
  `TaskListNum` bigint(20) NOT NULL,
  `DateTask` date NOT NULL DEFAULT '0001-01-01',
  `KeyNum` bigint(20) NOT NULL,
  `Descript` text NOT NULL,
  `TaskStatus` tinyint(4) NOT NULL,
  `IsRepeating` tinyint(4) NOT NULL,
  `DateType` tinyint(4) NOT NULL,
  `FromNum` bigint(20) NOT NULL,
  `ObjectType` tinyint(4) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `UserNum` bigint(20) NOT NULL,
  `DateTimeFinished` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `PriorityDefNum` bigint(20) NOT NULL,
  `ReminderGroupId` varchar(20) NOT NULL,
  `ReminderType` smallint(6) NOT NULL,
  `ReminderFrequency` int(11) NOT NULL,
  `DateTimeOriginal` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `DescriptOverride` varchar(255) NOT NULL,
  `IsReadOnly` tinyint(1) NOT NULL DEFAULT 0,
  `TriageCategory` bigint(20) NOT NULL,
  PRIMARY KEY (`TaskHistNum`),
  KEY `TaskNum` (`TaskNum`),
  KEY `SecDateTEdit` (`SecDateTEdit`),
  KEY `DateTStamp` (`DateTStamp`),
  KEY `KeyNum` (`KeyNum`),
  KEY `TriageCategory` (`TriageCategory`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;