CREATE TABLE `treatplan` (
  `TreatPlanNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `DateTP` date NOT NULL DEFAULT '0001-01-01',
  `Heading` varchar(255) DEFAULT '',
  `Note` text DEFAULT NULL,
  `Signature` text DEFAULT NULL,
  `SigIsTopaz` tinyint(1) NOT NULL,
  `ResponsParty` bigint(20) NOT NULL,
  `DocNum` bigint(20) NOT NULL,
  `TPStatus` tinyint(4) NOT NULL,
  `SecUserNumEntry` bigint(20) NOT NULL,
  `SecDateEntry` date NOT NULL DEFAULT '0001-01-01',
  `SecDateTEdit` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `UserNumPresenter` bigint(20) NOT NULL,
  `TPType` tinyint(4) NOT NULL,
  `SignaturePractice` text NOT NULL,
  `DateTSigned` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTPracticeSigned` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SignatureText` varchar(255) NOT NULL,
  `SignaturePracticeText` varchar(255) NOT NULL,
  `MobileAppDeviceNum` bigint(20) NOT NULL,
  PRIMARY KEY (`TreatPlanNum`),
  KEY `indexPatNum` (`PatNum`),
  KEY `DocNum` (`DocNum`),
  KEY `SecUserNumEntry` (`SecUserNumEntry`),
  KEY `UserNumPresenter` (`UserNumPresenter`),
  KEY `MobileAppDeviceNum` (`MobileAppDeviceNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;