CREATE TABLE `tsitranslog` (
  `TsiTransLogNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `UserNum` bigint(20) NOT NULL,
  `TransType` tinyint(4) NOT NULL,
  `TransDateTime` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ServiceType` tinyint(4) NOT NULL,
  `ServiceCode` tinyint(4) NOT NULL,
  `TransAmt` double NOT NULL,
  `AccountBalance` double NOT NULL,
  `FKeyType` tinyint(4) NOT NULL,
  `FKey` bigint(20) NOT NULL,
  `RawMsgText` varchar(1000) NOT NULL,
  `ClientId` varchar(25) NOT NULL,
  `TransJson` mediumtext NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `AggTransLogNum` bigint(20) NOT NULL,
  PRIMARY KEY (`TsiTransLogNum`),
  KEY `PatNum` (`PatNum`),
  KEY `UserNum` (`UserNum`),
  KEY `FKeyAndType` (`FKey`,`FKeyType`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `AggTransLogNum` (`AggTransLogNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;