CREATE TABLE `vaccinepat` (
  `VaccinePatNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `VaccineDefNum` bigint(20) NOT NULL,
  `DateTimeStart` datetime DEFAULT NULL,
  `DateTimeEnd` datetime DEFAULT NULL,
  `AdministeredAmt` float NOT NULL,
  `DrugUnitNum` bigint(20) NOT NULL,
  `LotNumber` varchar(255) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `Note` text NOT NULL,
  `FilledCity` varchar(255) NOT NULL,
  `FilledST` varchar(255) NOT NULL,
  `CompletionStatus` tinyint(4) NOT NULL,
  `AdministrationNoteCode` tinyint(4) NOT NULL,
  `UserNum` bigint(20) NOT NULL,
  `ProvNumOrdering` bigint(20) NOT NULL,
  `ProvNumAdminister` bigint(20) NOT NULL,
  `DateExpire` date NOT NULL DEFAULT '0001-01-01',
  `RefusalReason` tinyint(4) NOT NULL,
  `ActionCode` tinyint(4) NOT NULL,
  `AdministrationRoute` tinyint(4) NOT NULL,
  `AdministrationSite` tinyint(4) NOT NULL,
  PRIMARY KEY (`VaccinePatNum`),
  KEY `VaccineDefNum` (`VaccineDefNum`),
  KEY `DrugUnitNum` (`DrugUnitNum`),
  KEY `PatNum` (`PatNum`),
  KEY `UserNum` (`UserNum`),
  KEY `ProvNumOrdering` (`ProvNumOrdering`),
  KEY `ProvNumAdminister` (`ProvNumAdminister`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;