CREATE TABLE `vitalsign` (
  `VitalsignNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `Height` float NOT NULL,
  `Weight` float NOT NULL,
  `BpSystolic` smallint(6) NOT NULL,
  `BpDiastolic` smallint(6) NOT NULL,
  `DateTaken` date NOT NULL DEFAULT '0001-01-01',
  `HasFollowupPlan` tinyint(4) NOT NULL,
  `IsIneligible` tinyint(4) NOT NULL,
  `Documentation` text NOT NULL,
  `ChildGotNutrition` tinyint(4) NOT NULL,
  `ChildGotPhysCouns` tinyint(4) NOT NULL,
  `WeightCode` varchar(255) NOT NULL,
  `HeightExamCode` varchar(30) NOT NULL,
  `WeightExamCode` varchar(30) NOT NULL,
  `BMIExamCode` varchar(30) NOT NULL,
  `EhrNotPerformedNum` bigint(20) NOT NULL,
  `PregDiseaseNum` bigint(20) NOT NULL,
  `BMIPercentile` int(11) NOT NULL,
  `Pulse` int(11) NOT NULL,
  PRIMARY KEY (`VitalsignNum`),
  KEY `PatNum` (`PatNum`),
  KEY `WeightCode` (`WeightCode`),
  KEY `EhrNotPerformedNum` (`EhrNotPerformedNum`),
  KEY `PregDiseaseNum` (`PregDiseaseNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;