CREATE TABLE `webschedrecall` (
  `WebSchedRecallNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `ClinicNum` bigint(20) NOT NULL,
  `PatNum` bigint(20) NOT NULL,
  `RecallNum` bigint(20) NOT NULL,
  `DateTimeEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateDue` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `ReminderCount` int(11) NOT NULL,
  `DateTimeSent` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTimeSendFailed` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `SendStatus` tinyint(4) NOT NULL,
  `ShortGUID` varchar(255) NOT NULL,
  `ResponseDescript` text NOT NULL,
  `Source` tinyint(4) NOT NULL,
  `CommlogNum` bigint(20) NOT NULL,
  `MessageType` tinyint(4) NOT NULL,
  `MessageFk` bigint(20) NOT NULL,
  `ApptReminderRuleNum` bigint(20) NOT NULL,
  PRIMARY KEY (`WebSchedRecallNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `PatNum` (`PatNum`),
  KEY `RecallNum` (`RecallNum`),
  KEY `DateTimeReminderSent` (`DateTimeSent`),
  KEY `CommlogNum` (`CommlogNum`),
  KEY `MessageFk` (`MessageFk`),
  KEY `ApptReminderRuleNum` (`ApptReminderRuleNum`),
  KEY `DateTimeEntry` (`DateTimeEntry`),
  KEY `WebSchedRecallCovering` (`MessageType`,`SendStatus`,`ClinicNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;