CREATE TABLE `xwebresponse` (
  `XWebResponseNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `PatNum` bigint(20) NOT NULL,
  `ProvNum` bigint(20) NOT NULL,
  `ClinicNum` bigint(20) NOT NULL,
  `PaymentNum` bigint(20) NOT NULL,
  `DateTEntry` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `DateTUpdate` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TransactionStatus` tinyint(4) NOT NULL,
  `ResponseCode` int(11) NOT NULL,
  `XWebResponseCode` varchar(255) NOT NULL,
  `ResponseDescription` varchar(255) NOT NULL,
  `OTK` varchar(255) NOT NULL,
  `HpfUrl` text NOT NULL,
  `HpfExpiration` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TransactionID` varchar(255) NOT NULL,
  `TransactionType` varchar(255) NOT NULL,
  `Alias` varchar(255) NOT NULL,
  `CardType` varchar(255) NOT NULL,
  `CardBrand` varchar(255) NOT NULL,
  `CardBrandShort` varchar(255) NOT NULL,
  `MaskedAcctNum` varchar(255) NOT NULL,
  `Amount` double NOT NULL,
  `ApprovalCode` varchar(255) NOT NULL,
  `CardCodeResponse` varchar(255) NOT NULL,
  `ReceiptID` int(11) NOT NULL,
  `ExpDate` varchar(255) NOT NULL,
  `EntryMethod` varchar(255) NOT NULL,
  `ProcessorResponse` varchar(255) NOT NULL,
  `BatchNum` int(11) NOT NULL,
  `BatchAmount` double NOT NULL,
  `AccountExpirationDate` date NOT NULL DEFAULT '0001-01-01',
  `DebugError` text NOT NULL,
  `PayNote` text NOT NULL,
  `CCSource` tinyint(4) NOT NULL,
  `OrderId` varchar(255) NOT NULL,
  `EmailResponse` varchar(255) NOT NULL,
  `LogGuid` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`XWebResponseNum`),
  KEY `PatNum` (`PatNum`),
  KEY `ProvNum` (`ProvNum`),
  KEY `ClinicNum` (`ClinicNum`),
  KEY `PaymentNum` (`PaymentNum`),
  KEY `DateTUpdate` (`DateTUpdate`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;